[package]
name = "os-workspace"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[package.metadata.bootimage]
build-command = ["build", "--target", "x86_64-unknown-none"]

[workspace]
resolver = "2"
members = [
    "kernel",
    "kernel-bin",
    "xtask",
    "userland",
    "libc-lite",
]
default-members = [
    "kernel",
    "userland"
]

[patch.crates-io]
bootloader = { path = "third_party/bootloader" }
bootloader-x86_64-bios-stage-2 = { path = "third_party/bootloader/stage-2" }
